repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
  hooks:
    -   id: check-merge-conflict
    -   id: check-toml
    -   id: check-yaml
    -   id: debug-statements
    -   id: end-of-file-fixer
    -   id: no-commit-to-branch
        args: [--branch, master]
    -   id: requirements-txt-fixer
        exclude: ^requirements-dev\.txt$
    -   id: trailing-whitespace
# - repo: https://github.com/astral-sh/ruff-pre-commit
#   rev: v0.5.5
#   hooks:
#     - id: ruff
#       args: [ --fix ]
#     - id: ruff-format
- repo: https://github.com/PyCQA/isort
  rev: 5.13.2
  hooks:
    - id: isort
      name: isort
      args: ["--profile=black"]
# - repo: https://github.com/asottile/pyupgrade
#   rev: v2.29.1
#   hooks:
#     - id: pyupgrade
#       args: [--py37-plus]
# - repo: https://github.com/psf/black
#   rev: 24.4.2
#   hooks:
#     - id: black
# - repo: https://github.com/PyCQA/pylint
#   rev: v3.2.6
#   hooks:
#     - id: pylint
#       args:
#         [
#         "--rcfile=.pylintrc",
#         ]

# - repo: https://github.com/nbQA-dev/nbQA
#   rev: 1.8.5
#   hooks:
#     - id: nbqa-ruff
#       args: ["--fix"]
#     - id: nbqa-black
#       args: ["--line-length=88"]
#     - id: nbqa-pyupgrade
#       args: [--py36-plus]
#     - id: nbqa-isort
#       args: ["--profile=black"]
#     - id: nbqa-pylint
#       args: [--rcfile=.pylintrc]
