version: 2

sphinx:
    configuration: docs/source/conf.py

python:
   install:
   - method: pip
     path: .

conda:
  environment: "conda-envs/environment-docs.yml"

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.11"
