name: pytest

on:
  push:
    branches: [ main ]
    paths-ignore: # prevents workflow execution when only these types of files are modified
      - "**.ipynb"
      - "**.md" # wildcards prevent file in any repo dir from trigering workflow
      - "**.rst"
      - "**.txt"
      - "**.ya?ml" # captures both .yml and .yaml
      - "LICENSE"
      - ".gitignore"
  pull_request:
    branches: [ main ]
    paths-ignore: # prevents workflow execution when only these types of files are modified
      - "**.md" # wildcards prevent file in any repo dir from trigering workflow
      - "**.rst"
      - "**.txt"
      - "**.ya?ml" # captures both .yml and .yaml
      - "LICENSE"
      - ".gitignore"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:
  pytest:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest] # macos-latest
        floatx: [float64]
        # python-version: ["3.12"]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    env:
      PYTENSOR_FLAGS: floatX=${{ matrix.floatx }},gcc__cxxflags='-march=native'
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
          miniforge-version: "latest"
          activate-environment: stratmc-dev
          channels: conda-forge,defaults
          channel-priority: true
          # channel-priority: strict
          # environment-file: conda-envs/environment-dev.yml
          # use-only-tar-bz2: true # IMPORTANT: This needs to be set for caching to work properly!

      - name: Install stratmc
        run: |
          conda activate stratmc-dev
          python -m pip install -e ".[test]"

      - name: Run pytest
        shell: bash -l {0}
        run: |
          conda activate stratmc-dev
          python -m pytest --cov=stratmc --cov-report=xml --cov-report term stratmc/tests/

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          directory: ./coverage/reports/
          env_vars: OS,PYTHON
          fail_ci_if_error: false
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml
          name: codecov-umbrella
          path_to_write_report: ./coverage/codecov_report.txt
          verbose: true
